[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.115.5",
    "flask>=3.1.0",
    "pydantic==2.10.0",
    "replit>=4.1.0",
    "uvicorn==0.32.1",
]
